# Generated by Django 3.2 on 2023-05-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribe_no_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='no_self_follow',
        ),
    ]
